postscript: |
  Edit or delete this

hostname: static-zek.ljudje.si

asset_host: zek.imgix.net

facebook_url: https://www.facebook.com/themihaartnak
facebook_title: Like Facebook page
email_address: miha@artnak.net
email_title: Send email
instagram_url: https://www.instagram.com/streets_artnak/
instagram_title: Check Instagram
