title: Artur ♦ ZEK
og_description: a.k.a. The Miha Artnak a.k.a. human
og_image: http://artur.zekcrew.com/assets/projects/zajci/zajc-rdec-2.jpg

postscript: |
  

  <p style='text-align: center; font-weight: bold;'>If you find any joy and value in what I do, please consider donating Bitcoin to this address </p>
  
  <img src="/assets/projects/fake-good-news-ep1s1/qr-btc.jpg" />

  <p style='text-align: center;'><a style='text-decoration: none; background: #FFB119; color: white; font-weight: bold; padding: 0.5rem; border-radius: 4px;'>1N968bEU9bahcWQazkx9PJF4MEAtbBwe9T</a></p>

  <p style='text-align: center;'>[About The Miha Artnak](https://docs.google.com/document/d/1vJw2Uhh4Qugvt0ww_UMp3mLEAjIte-bwdVyVCOPMQLY/edit?usp=sharing) | [ZEK Crew](http://zekcrew.com) | [Studio People](http://people.ooo)</p>


hostname: localhost:9080
asset_host: artur.netlify.com

facebook_url: https://www.facebook.com/themihaartnak
facebook_title: Like Facebook page
email_address: miha.artnak@gmail.com
email_title: Send email
instagram_url: https://www.instagram.com/streets_artnak/
instagram_title: Check Instagram

analytics_id: UA-43735632-10
global_scripts: |
  <!-- Facebook Pixel Code -->
  <script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '126849774684506'); // Insert your pixel ID here.
  fbq('track', 'PageView');
  </script>
  <noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=126849774684506&ev=PageView&noscript=1"
  /></noscript>
  <!-- DO NOT MODIFY -->
  <!-- End Facebook Pixel Code -->