title: Artur ♦ ZEK
og_description: a.k.a. The Miha Artnak a.k.a. human
og_image: http://artur.zekcrew.com/assets/projects/zajci/zajc-rdec-2.jpg

postscript: |
  <center> <b> [About The Miha Artnak](https://docs.google.com/document/d/1vJw2Uhh4Qugvt0ww_UMp3mLEAjIte-bwdVyVCOPMQLY/edit?usp=sharing) | [ZEK Crew](http://zekcrew.com) | [Studio People](http://people.ooo)</small> </center> 

hostname: localhost:9080
asset_host: artur.netlify.com

facebook_url: https://www.facebook.com/themihaartnak
facebook_title: Like Facebook page
email_address: miha.artnak@gmail.com
email_title: Send email
instagram_url: https://www.instagram.com/streets_artnak/
instagram_title: Check Instagram

analytics_id: UA-43735632-10