title: Artur ♦ ZEK
og_description: a.k.a. The Miha Artnak is a human
og_image: http://artur.zekcrew.com/assets/projects/zajci/zajc-rdec-2.jpg

postscript: |
  <center> <b>A R T U R / Z E K </b>  a.k.a. [The Miha Artnak](https://docs.google.com/document/d/1vJw2Uhh4Qugvt0ww_UMp3mLEAjIte-bwdVyVCOPMQLY/edit?usp=sharing) is a [human](http://people.ooo)</small> </center> 

hostname: localhost:9080
asset_host: artur.netlify.com

facebook_url: https://www.facebook.com/themihaartnak
facebook_title: Like Facebook page
email_address: miha@artnak.net
email_title: Send email
instagram_url: https://www.instagram.com/streets_artnak/
instagram_title: Check Instagram

analytics_id: UA-43735632-10
